# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=3)),
                ('crest_small_url', models.URLField()),
                ('crest_medium_url', models.URLField()),
                ('crest_large_url', models.URLField()),
            ],
        ),
    ]
