# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170617_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='id_clube',
        ),
        migrations.AddField(
            model_name='clube',
            name='escudo_30x30',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clube',
            name='escudo_45x45',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clube',
            name='escudo_60x60',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clube',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
