# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170718_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clube_casa_posicao', models.IntegerField()),
                ('clube_visitante_posicao', models.IntegerField()),
                ('aproveitamento_mandante', models.CharField(max_length=5)),
                ('aproveitamento_visitante', models.CharField(max_length=5)),
                ('placar_oficial_mandante', models.IntegerField()),
                ('placar_oficial_visitante', models.IntegerField()),
                ('partida_data', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('valida', models.BooleanField()),
                ('url_confronto', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='clube',
            name='escudo_30x30',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='clube',
            name='escudo_45x45',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='clube',
            name='escudo_60x60',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='partida',
            name='clube_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='core.Clube'),
        ),
        migrations.AddField(
            model_name='partida',
            name='clube_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='core.Clube'),
        ),
    ]
