# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170721_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
