# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atleta_posicao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviacao', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=20)),
                ('pontuacao', models.IntegerField(default=0)),
            ],
        ),
    ]
