# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pontuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('rodada', models.IntegerField()),
                ('pontos_num', models.FloatField()),
                ('preco_num', models.FloatField()),
                ('variacao_num', models.FloatField()),
                ('media_num', models.FloatField()),
                ('jogos_num', models.IntegerField(default=0)),
                ('FS', models.IntegerField(default=0)),
                ('PE', models.IntegerField(default=0)),
                ('A', models.IntegerField(default=0)),
                ('FT', models.IntegerField(default=0)),
                ('FD', models.IntegerField(default=0)),
                ('FF', models.IntegerField(default=0)),
                ('G', models.IntegerField(default=0)),
                ('I', models.IntegerField(default=0)),
                ('PP', models.IntegerField(default=0)),
                ('RB', models.IntegerField(default=0)),
                ('FC', models.IntegerField(default=0)),
                ('GC', models.IntegerField(default=0)),
                ('CA', models.IntegerField(default=0)),
                ('CV', models.IntegerField(default=0)),
                ('SG', models.IntegerField(default=0)),
                ('DD', models.IntegerField(default=0)),
                ('DP', models.IntegerField(default=0)),
                ('GS', models.IntegerField(default=0)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atleta')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Clube')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Posicao')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Status')),
            ],
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='abreviacao',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
