# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170727_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='media_num',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scout',
            name='pontos_num',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scout',
            name='preco_num',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scout',
            name='variacao_num',
            field=models.FloatField(default=0),
        ),
    ]
