# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170727_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scout',
            old_name='A',
            new_name='scouts_A',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='CA',
            new_name='scouts_CA',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='CV',
            new_name='scouts_CV',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='DD',
            new_name='scouts_DD',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='DP',
            new_name='scouts_DP',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='FC',
            new_name='scouts_FC',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='FD',
            new_name='scouts_FD',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='FF',
            new_name='scouts_FF',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='FS',
            new_name='scouts_FS',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='FT',
            new_name='scouts_FT',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='G',
            new_name='scouts_G',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='GC',
            new_name='scouts_GC',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='GS',
            new_name='scouts_GS',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='I',
            new_name='scouts_I',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='PE',
            new_name='scouts_PE',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='PP',
            new_name='scouts_PP',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='RB',
            new_name='scouts_RB',
        ),
        migrations.RenameField(
            model_name='scout',
            old_name='SG',
            new_name='scouts_SG',
        ),
    ]
