# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170728_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scout',
            name='ano',
        ),
        migrations.AddField(
            model_name='scout',
            name='partida',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Partida'),
            preserve_default=False,
        ),
    ]
